server:
  port: 3000

spring:
  application:
    name: carpool-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/carpool
    username: postgres
    password: Ljr19980221@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
